/*
 * This file is generated by jOOQ.
 */
package io.lumine.achievements.storage.sql.jooq.tables.records;


import io.lumine.achievements.storage.sql.jooq.tables.MythicachievementsProfile;

import io.lumine.mythic.bukkit.utils.lib.jooq.Field;
import io.lumine.mythic.bukkit.utils.lib.jooq.Record1;
import io.lumine.mythic.bukkit.utils.lib.jooq.Record2;
import io.lumine.mythic.bukkit.utils.lib.jooq.Row2;
import io.lumine.mythic.bukkit.utils.lib.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileRecord extends UpdatableRecordImpl<ProfileRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mythicachievements_profile.uuid</code>.
     */
    public void setUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mythicachievements_profile.uuid</code>.
     */
    public String getUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mythicachievements_profile.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mythicachievements_profile.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return MythicachievementsProfile.MYTHICACHIEVEMENTS_PROFILE.UUID;
    }

    @Override
    public Field<String> field2() {
        return MythicachievementsProfile.MYTHICACHIEVEMENTS_PROFILE.NAME;
    }

    @Override
    public String component1() {
        return getUuid();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String value1() {
        return getUuid();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public ProfileRecord value1(String value) {
        setUuid(value);
        return this;
    }

    @Override
    public ProfileRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProfileRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MythicachievementsProfileRecord
     */
    public ProfileRecord() {
        super(MythicachievementsProfile.MYTHICACHIEVEMENTS_PROFILE);
    }

    /**
     * Create a detached, initialised MythicachievementsProfileRecord
     */
    public ProfileRecord(String uuid, String name) {
        super(MythicachievementsProfile.MYTHICACHIEVEMENTS_PROFILE);

        setUuid(uuid);
        setName(name);
    }
}
