/*
 * This file is generated by jOOQ.
 */
package io.lumine.achievements.storage.sql.jooq.tables.records;


import io.lumine.achievements.storage.sql.jooq.tables.MythicachievementsProfileCompleted;

import io.lumine.mythic.bukkit.utils.lib.jooq.Field;
import io.lumine.mythic.bukkit.utils.lib.jooq.Record2;
import io.lumine.mythic.bukkit.utils.lib.jooq.Record4;
import io.lumine.mythic.bukkit.utils.lib.jooq.Row4;
import io.lumine.mythic.bukkit.utils.lib.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileCompletedRecord extends UpdatableRecordImpl<ProfileCompletedRecord> implements Record4<String, String, Long, Byte> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>mythicachievements_profile_completed.profile_uuid</code>.
     */
    public void setProfileUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>mythicachievements_profile_completed.profile_uuid</code>.
     */
    public String getProfileUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mythicachievements_profile_completed.achievement</code>.
     */
    public void setAchievement(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mythicachievements_profile_completed.achievement</code>.
     */
    public String getAchievement() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>mythicachievements_profile_completed.completed_time</code>.
     */
    public void setCompletedTime(Long value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>mythicachievements_profile_completed.completed_time</code>.
     */
    public Long getCompletedTime() {
        return (Long) get(2);
    }

    /**
     * Setter for
     * <code>mythicachievements_profile_completed.collected_loot</code>.
     */
    public void setCollectedLoot(Byte value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>mythicachievements_profile_completed.collected_loot</code>.
     */
    public Byte getCollectedLoot() {
        return (Byte) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, Long, Byte> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, Long, Byte> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return MythicachievementsProfileCompleted.MYTHICACHIEVEMENTS_PROFILE_COMPLETED.PROFILE_UUID;
    }

    @Override
    public Field<String> field2() {
        return MythicachievementsProfileCompleted.MYTHICACHIEVEMENTS_PROFILE_COMPLETED.ACHIEVEMENT;
    }

    @Override
    public Field<Long> field3() {
        return MythicachievementsProfileCompleted.MYTHICACHIEVEMENTS_PROFILE_COMPLETED.COMPLETED_TIME;
    }

    @Override
    public Field<Byte> field4() {
        return MythicachievementsProfileCompleted.MYTHICACHIEVEMENTS_PROFILE_COMPLETED.COLLECTED_LOOT;
    }

    @Override
    public String component1() {
        return getProfileUuid();
    }

    @Override
    public String component2() {
        return getAchievement();
    }

    @Override
    public Long component3() {
        return getCompletedTime();
    }

    @Override
    public Byte component4() {
        return getCollectedLoot();
    }

    @Override
    public String value1() {
        return getProfileUuid();
    }

    @Override
    public String value2() {
        return getAchievement();
    }

    @Override
    public Long value3() {
        return getCompletedTime();
    }

    @Override
    public Byte value4() {
        return getCollectedLoot();
    }

    @Override
    public ProfileCompletedRecord value1(String value) {
        setProfileUuid(value);
        return this;
    }

    @Override
    public ProfileCompletedRecord value2(String value) {
        setAchievement(value);
        return this;
    }

    @Override
    public ProfileCompletedRecord value3(Long value) {
        setCompletedTime(value);
        return this;
    }

    @Override
    public ProfileCompletedRecord value4(Byte value) {
        setCollectedLoot(value);
        return this;
    }

    @Override
    public ProfileCompletedRecord values(String value1, String value2, Long value3, Byte value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MythicachievementsProfileCompletedRecord
     */
    public ProfileCompletedRecord() {
        super(MythicachievementsProfileCompleted.MYTHICACHIEVEMENTS_PROFILE_COMPLETED);
    }

    /**
     * Create a detached, initialised MythicachievementsProfileCompletedRecord
     */
    public ProfileCompletedRecord(String profileUuid, String achievement, Long completedTime, Byte collectedLoot) {
        super(MythicachievementsProfileCompleted.MYTHICACHIEVEMENTS_PROFILE_COMPLETED);

        setProfileUuid(profileUuid);
        setAchievement(achievement);
        setCompletedTime(completedTime);
        setCollectedLoot(collectedLoot);
    }
}
