/*
 * This file is generated by jOOQ.
 */
package io.lumine.achievements.storage.sql.jooq.tables.records;


import io.lumine.achievements.storage.sql.jooq.tables.MythicachievementsProfileProgress;

import io.lumine.mythic.bukkit.utils.lib.jooq.Field;
import io.lumine.mythic.bukkit.utils.lib.jooq.Record3;
import io.lumine.mythic.bukkit.utils.lib.jooq.Record4;
import io.lumine.mythic.bukkit.utils.lib.jooq.Row4;
import io.lumine.mythic.bukkit.utils.lib.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileProgressRecord extends UpdatableRecordImpl<ProfileProgressRecord> implements Record4<String, String, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>mythicachievements_profile_progress.profile_uuid</code>.
     */
    public void setProfileUuid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>mythicachievements_profile_progress.profile_uuid</code>.
     */
    public String getProfileUuid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>mythicachievements_profile_progress.achievement</code>.
     */
    public void setAchievement(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mythicachievements_profile_progress.achievement</code>.
     */
    public String getAchievement() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mythicachievements_profile_progress.criteria</code>.
     */
    public void setCriteria(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mythicachievements_profile_progress.criteria</code>.
     */
    public String getCriteria() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mythicachievements_profile_progress.progress</code>.
     */
    public void setProgress(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>mythicachievements_profile_progress.progress</code>.
     */
    public Integer getProgress() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<String, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<String, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<String, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return MythicachievementsProfileProgress.MYTHICACHIEVEMENTS_PROFILE_PROGRESS.PROFILE_UUID;
    }

    @Override
    public Field<String> field2() {
        return MythicachievementsProfileProgress.MYTHICACHIEVEMENTS_PROFILE_PROGRESS.ACHIEVEMENT;
    }

    @Override
    public Field<String> field3() {
        return MythicachievementsProfileProgress.MYTHICACHIEVEMENTS_PROFILE_PROGRESS.CRITERIA;
    }

    @Override
    public Field<Integer> field4() {
        return MythicachievementsProfileProgress.MYTHICACHIEVEMENTS_PROFILE_PROGRESS.PROGRESS;
    }

    @Override
    public String component1() {
        return getProfileUuid();
    }

    @Override
    public String component2() {
        return getAchievement();
    }

    @Override
    public String component3() {
        return getCriteria();
    }

    @Override
    public Integer component4() {
        return getProgress();
    }

    @Override
    public String value1() {
        return getProfileUuid();
    }

    @Override
    public String value2() {
        return getAchievement();
    }

    @Override
    public String value3() {
        return getCriteria();
    }

    @Override
    public Integer value4() {
        return getProgress();
    }

    @Override
    public ProfileProgressRecord value1(String value) {
        setProfileUuid(value);
        return this;
    }

    @Override
    public ProfileProgressRecord value2(String value) {
        setAchievement(value);
        return this;
    }

    @Override
    public ProfileProgressRecord value3(String value) {
        setCriteria(value);
        return this;
    }

    @Override
    public ProfileProgressRecord value4(Integer value) {
        setProgress(value);
        return this;
    }

    @Override
    public ProfileProgressRecord values(String value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MythicachievementsProfileProgressRecord
     */
    public ProfileProgressRecord() {
        super(MythicachievementsProfileProgress.MYTHICACHIEVEMENTS_PROFILE_PROGRESS);
    }

    /**
     * Create a detached, initialised MythicachievementsProfileProgressRecord
     */
    public ProfileProgressRecord(String profileUuid, String achievement, String criteria, Integer progress) {
        super(MythicachievementsProfileProgress.MYTHICACHIEVEMENTS_PROFILE_PROGRESS);

        setProfileUuid(profileUuid);
        setAchievement(achievement);
        setCriteria(criteria);
        setProgress(progress);
    }
}
