/*
 * This file is generated by jOOQ.
 */
package io.lumine.achievements.storage.sql.jooq;


import io.lumine.achievements.storage.sql.jooq.tables.MythicachievementsProfile;
import io.lumine.achievements.storage.sql.jooq.tables.MythicachievementsProfileCompleted;
import io.lumine.achievements.storage.sql.jooq.tables.MythicachievementsProfileProgress;

import java.util.Arrays;
import java.util.List;

import io.lumine.mythic.bukkit.utils.lib.jooq.Catalog;
import io.lumine.mythic.bukkit.utils.lib.jooq.Table;
import io.lumine.mythic.bukkit.utils.lib.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>mythicachievements_profile</code>.
     */
    public final MythicachievementsProfile MYTHICACHIEVEMENTS_PROFILE = MythicachievementsProfile.MYTHICACHIEVEMENTS_PROFILE;

    /**
     * The table <code>mythicachievements_profile_completed</code>.
     */
    public final MythicachievementsProfileCompleted MYTHICACHIEVEMENTS_PROFILE_COMPLETED = MythicachievementsProfileCompleted.MYTHICACHIEVEMENTS_PROFILE_COMPLETED;

    /**
     * The table <code>mythicachievements_profile_progress</code>.
     */
    public final MythicachievementsProfileProgress MYTHICACHIEVEMENTS_PROFILE_PROGRESS = MythicachievementsProfileProgress.MYTHICACHIEVEMENTS_PROFILE_PROGRESS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            MythicachievementsProfile.MYTHICACHIEVEMENTS_PROFILE,
            MythicachievementsProfileCompleted.MYTHICACHIEVEMENTS_PROFILE_COMPLETED,
            MythicachievementsProfileProgress.MYTHICACHIEVEMENTS_PROFILE_PROGRESS
        );
    }
}
