/*
 * This file is generated by jOOQ.
 */
package io.lumine.achievements.storage.sql.jooq;


import io.lumine.achievements.storage.sql.jooq.tables.MythicachievementsProfile;
import io.lumine.achievements.storage.sql.jooq.tables.MythicachievementsProfileCompleted;
import io.lumine.achievements.storage.sql.jooq.tables.MythicachievementsProfileProgress;
import io.lumine.achievements.storage.sql.jooq.tables.records.ProfileCompletedRecord;
import io.lumine.achievements.storage.sql.jooq.tables.records.ProfileProgressRecord;
import io.lumine.achievements.storage.sql.jooq.tables.records.ProfileRecord;

import io.lumine.mythic.bukkit.utils.lib.jooq.ForeignKey;
import io.lumine.mythic.bukkit.utils.lib.jooq.TableField;
import io.lumine.mythic.bukkit.utils.lib.jooq.UniqueKey;
import io.lumine.mythic.bukkit.utils.lib.jooq.impl.DSL;
import io.lumine.mythic.bukkit.utils.lib.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ProfileRecord> KEY_MYTHICACHIEVEMENTS_PROFILE_PRIMARY = Internal.createUniqueKey(MythicachievementsProfile.MYTHICACHIEVEMENTS_PROFILE, DSL.name("KEY_mythicachievements_profile_PRIMARY"), new TableField[] { MythicachievementsProfile.MYTHICACHIEVEMENTS_PROFILE.UUID }, true);
    public static final UniqueKey<ProfileCompletedRecord> KEY_MYTHICACHIEVEMENTS_PROFILE_COMPLETED_PRIMARY = Internal.createUniqueKey(MythicachievementsProfileCompleted.MYTHICACHIEVEMENTS_PROFILE_COMPLETED, DSL.name("KEY_mythicachievements_profile_completed_PRIMARY"), new TableField[] { MythicachievementsProfileCompleted.MYTHICACHIEVEMENTS_PROFILE_COMPLETED.ACHIEVEMENT, MythicachievementsProfileCompleted.MYTHICACHIEVEMENTS_PROFILE_COMPLETED.PROFILE_UUID }, true);
    public static final UniqueKey<ProfileProgressRecord> KEY_MYTHICACHIEVEMENTS_PROFILE_PROGRESS_PRIMARY = Internal.createUniqueKey(MythicachievementsProfileProgress.MYTHICACHIEVEMENTS_PROFILE_PROGRESS, DSL.name("KEY_mythicachievements_profile_progress_PRIMARY"), new TableField[] { MythicachievementsProfileProgress.MYTHICACHIEVEMENTS_PROFILE_PROGRESS.CRITERIA, MythicachievementsProfileProgress.MYTHICACHIEVEMENTS_PROFILE_PROGRESS.ACHIEVEMENT, MythicachievementsProfileProgress.MYTHICACHIEVEMENTS_PROFILE_PROGRESS.PROFILE_UUID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ProfileCompletedRecord, ProfileRecord> MYTHICACHIEVEMENTS_PROFILE_COMPLETED_FK = Internal.createForeignKey(MythicachievementsProfileCompleted.MYTHICACHIEVEMENTS_PROFILE_COMPLETED, DSL.name("mythicachievements_profile_completed_fk"), new TableField[] { MythicachievementsProfileCompleted.MYTHICACHIEVEMENTS_PROFILE_COMPLETED.PROFILE_UUID }, Keys.KEY_MYTHICACHIEVEMENTS_PROFILE_PRIMARY, new TableField[] { MythicachievementsProfile.MYTHICACHIEVEMENTS_PROFILE.UUID }, true);
    public static final ForeignKey<ProfileProgressRecord, ProfileRecord> MYTHICACHIEVEMENTS_PROFILE_PROGRESS_UUID_FK = Internal.createForeignKey(MythicachievementsProfileProgress.MYTHICACHIEVEMENTS_PROFILE_PROGRESS, DSL.name("mythicachievements_profile_progress_uuid_fk"), new TableField[] { MythicachievementsProfileProgress.MYTHICACHIEVEMENTS_PROFILE_PROGRESS.PROFILE_UUID }, Keys.KEY_MYTHICACHIEVEMENTS_PROFILE_PRIMARY, new TableField[] { MythicachievementsProfile.MYTHICACHIEVEMENTS_PROFILE.UUID }, true);
}
