/*
 * This file is generated by jOOQ.
 */
package io.lumine.achievements.storage.sql.jooq;


import io.lumine.achievements.storage.sql.jooq.tables.MythicachievementsProfile;
import io.lumine.achievements.storage.sql.jooq.tables.MythicachievementsProfileCompleted;
import io.lumine.achievements.storage.sql.jooq.tables.MythicachievementsProfileProgress;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>mythicachievements_profile</code>.
     */
    public static final MythicachievementsProfile MYTHICACHIEVEMENTS_PROFILE = MythicachievementsProfile.MYTHICACHIEVEMENTS_PROFILE;

    /**
     * The table <code>mythicachievements_profile_completed</code>.
     */
    public static final MythicachievementsProfileCompleted MYTHICACHIEVEMENTS_PROFILE_COMPLETED = MythicachievementsProfileCompleted.MYTHICACHIEVEMENTS_PROFILE_COMPLETED;

    /**
     * The table <code>mythicachievements_profile_progress</code>.
     */
    public static final MythicachievementsProfileProgress MYTHICACHIEVEMENTS_PROFILE_PROGRESS = MythicachievementsProfileProgress.MYTHICACHIEVEMENTS_PROFILE_PROGRESS;
}
